### PR TITLE
Option to limit the number of internal local anchors

### PR DESCRIPTION
**Pull request by fast-slow-still**
For large spaces and at the usual density of anchor placement, WLT can bog down performance by creating more WorldAnchors than the device is capable of processing under budget.

The processing of the anchor graph has still never shown up as a significant percentage of each frame's CPU usage. But each WorldAnchor in the scene incurs some processing cost, whether it is contributing to the world-locking or not.

To combat this, the user is given two degrees of freedom to explore trading off higher performance for (possibly) lower accuracy.

The first is to lower the density of the internal anchor graph. This is done via increasing the distance between anchor nodes with the MinNewAnchorDistance. The longer the edge length, the lower the density of anchors, and so the fewer anchors required to cover the same area.

The second is to directly limit the number of internal anchors. In this initial implementation, bringing down the number of anchors (when it is over the limit) is accomplished by recycling the anchor furthest from the camera, it being assumed to be the least relevant.

Early tests show this relatively naïve (but extremely low cost) algorithm to still provide excellent stability. Even when leaving a space recycles all anchors in that space, upon reentering the space (and filling it with new anchors) object placement relative to the physical world remains constant.

By default, there is no explicit limit on the number of local anchors in use.

image

These options are available in the Anchor Management section of the World Locking Context, on the scene's WorldLockingManager node.

### CODE REVIEW

**Comment by fast-slow-still** [comment]
Fixes: #61 

At least as a first iteration. We'll need to see how well this addresses the issues, before proceeding with more complex recycling algorithms. But at the least this PR demonstrates an ability to recycle WorldAnchor resources, if not the best way to choose which anchors to recycle.

**Comment by zantiu** [comment]
Just adding some test data for Hololens 2 for future reference:
- Framerate stays stable at 60 FPS till about 160 anchors
- After that FPS drops linearly to reach about 30 FPS at 600 anchors

So 160 anchors is a good setting to start from.

**Comment by fast-slow-still** [comment]
Very kind of you to share your findings, I'm sure the community will find it helpful!

**Pull request merged**
