### PR TITLE
WLT AlignSubTree SpacePin Mesh Visualization feature

### PR DESCRIPTION
**Pull request by creckd**
Steps to test the feature:

1. Drag the SpacePinVisualizer prefab into the root of the SpacePinPartial scene.
2. Create SpacePins by manipulating the spheres.
3. Debug visuals should appear showing the weights and distribution of the currently active pins.

### CODE REVIEW

**Comment by fast-slow-still** [comment]
@creckd Sorry to be so long getting to this. I am not seeing any diagnostics/visualizations when I manipulate the SpacePin spheres. This is my setup in Unity, does it look correct?

image

Where should I be seeing the Debug Visuals? Could you post a MRC photo showing what I should look for?

Here's what I see in HL2. Note that I also added the AnchorGraphVisual.

NoVisual

There were no unusual messages in UnityPlayer.log.

**Comment by creckd** [comment]
Thats unusual, your setup does look okay.

Debug pins and a wireframe should appear below your feet. (~1.65 meters downwards from your headset position)

You should see something like this after manipulating a few pins :

image

Are you using HoloRemote while testing this feature?

**Comment by fast-slow-still** [comment]
Looks awesome! No, no Remoting, I'm deploying straight to device, HL2, Release, ARM64.

**Comment by fast-slow-still** [comment]
If you get a chance to try it on a clean clone of your branch, maybe a file got missed? Like I mentioned, no errors or warnings or exceptions in UnityPlayer.log.

I'll have a chance to dig deeper and do some debugging this weekend.

**Comment by creckd** [comment]
There seeemed to be an error regarding script execution order where the AlignmentManager has been already created before the SpacePinMeshVisualizer could've subscribed for the event of the creation.

I've pushed a slight change, could you check it on your side again?

Thanks!

**Comment by fast-slow-still** [comment]
Yes, Unity initialization order is frustratingly vague. I'll give it a try. Thanks!

**Comment by fast-slow-still** [comment]
Looks like that was it. The feature looks very useful! I'll try to get it merged in today.

**Comment by fast-slow-still** [comment]
I would like to extend it to support multiple AlignSubtrees within a single scene. But first I will get it merged in and documented. I'll make a separate issue to track that extension. #90

**Review by fast-slow-still — APPROVED** [review]
Looks good, more notes in PR comments. Thanks for the great contribution!

**Pull request merged**
